[Interface]
Address = 10.44.2.180/32
PrivateKey = uCVtdoYsJ8LDt9KthdKgpxstTgNxmpBDSV0Aq0nqyHk=
MTU = 1300

[Peer]
PublicKey = I3iqx67M/KpGgdYhBPBl14JGmP1b41enwrW5rOx3Kn8=
Endpoint = 91.98.148.10:51820
AllowedIPs = 10.44.0.0/15
PersistentKeepalive = 5
