[Interface]
Address = 10.44.2.180/32
PrivateKey = qHxu6kFSEYLjKEnA/YgKKZ/S43rkqhP7iaCVkaPy2Wk=
MTU = 1300

[Peer]
PublicKey = El/wrG3mKUKmL/EsCsGkgFYzaG5nocYnDPSdCm4t1gg=
Endpoint = 91.98.148.10:51820
AllowedIPs = 10.44.0.0/15
PersistentKeepalive = 5
